### ISSUE TITLE
MTD VAT Period Key generation Issue

### ISSUE THREAD

**Issue by rajcapium** [hmrc/vat-sign-up#43]
Hi All,

I am developing MTD VAT for my software.While submitting the VAT I need generate the period key which must be the string of four alphanumeric characters.  Occasionally the format includes the # symbol, which must be  URL-encoded.

I am using the following code to generate the string.

const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
return new string(Enumerable.Repeat(chars, 4)
              .Select(s => s[random.Next(s.Length)]).ToArray());

But the problem is some time it is accepting the string while I generated some times it is saying that period key is in valid.Is their any specific format for generating the period key.

could any one please help me on this..

thanks in advance..

**Comment by kabuumu** [comment]
Hi,
I think you've got the wrong repository. You're looking for
https://github.com/hmrc/vat-api

Thanks,
Rob
